INSERT INTO PRODUTO (ID,EAN,DESCRICAO,MARCA,MODELO,VALORUNITARIO) VALUES (1,"12345","JOGO DE VELAS"       ,"CHAMPION","MD1", 35);
INSERT INTO PRODUTO (ID,EAN,DESCRICAO,MARCA,MODELO,VALORUNITARIO) VALUES (2,"54321","BICO INJETOR"        ,"GM"      ,"MD2", 373);
INSERT INTO PRODUTO (ID,EAN,DESCRICAO,MARCA,MODELO,VALORUNITARIO) VALUES (3,"09876","BOMBA DE COMBUSTÍVEL","BOCH"    ,"MD1", 282);
INSERT INTO PRODUTO (ID,EAN,DESCRICAO,MARCA,MODELO,VALORUNITARIO) VALUES (4,"67890","BOBINA RENAULT"      ,"RENAULT" ,"MD3", 151);