INSERT INTO UF (descricao,sigla) VALUES ("Acre",                  "AC");
INSERT INTO UF (descricao,sigla) VALUES ("Alagoas",               "AL");
INSERT INTO UF (descricao,sigla) VALUES ("Amapá",                  "AP");
INSERT INTO UF (descricao,sigla) VALUES ("Amazonas",              "AM");
INSERT INTO UF (descricao,sigla) VALUES ("Bahia",                 "BA");
INSERT INTO UF (descricao,sigla) VALUES ("Ceará",                  "CE");
INSERT INTO UF (descricao,sigla) VALUES ("Distrito Federal",      "DF");
INSERT INTO UF (descricao,sigla) VALUES ("Goiás",                  "GO");
INSERT INTO UF (descricao,sigla) VALUES ("Espírito Santo",         "ES");
INSERT INTO UF (descricao,sigla) VALUES ("Maranhão",               "MA");
INSERT INTO UF (descricao,sigla) VALUES ("Mato Grosso",           "MT");
INSERT INTO UF (descricao,sigla) VALUES ("Mato Grosso do Sul",    "MS");
INSERT INTO UF (descricao,sigla) VALUES ("Minas Gerais",          "MG");
INSERT INTO UF (descricao,sigla) VALUES ("Pará",                   "PA");
INSERT INTO UF (descricao,sigla) VALUES ("Paraíba",               "PB");
INSERT INTO UF (descricao,sigla) VALUES ("Paraná",                 "PR");
INSERT INTO UF (descricao,sigla) VALUES ("Pernambuco",            "PE");
INSERT INTO UF (descricao,sigla) VALUES ("Piauí",                  "PI");
INSERT INTO UF (descricao,sigla) VALUES ("Rio de Janeiro",        "RJ");
INSERT INTO UF (descricao,sigla) VALUES ("Rio Grande do Norte",   "RN");
INSERT INTO UF (descricao,sigla) VALUES ("Rio Grande do Sul",     "RS");
INSERT INTO UF (descricao,sigla) VALUES ("Rondônia",               "RO");
INSERT INTO UF (descricao,sigla) VALUES ("Roraima",                "RR");
INSERT INTO UF (descricao,sigla) VALUES ("São Paulo",              "SP");
INSERT INTO UF (descricao,sigla) VALUES ("Santa Catarina",        "SC");
INSERT INTO UF (descricao,sigla) VALUES ("Sergipe",               "SE");
INSERT INTO UF (descricao,sigla) VALUES ("Tocantins",             "TO");