INSERT INTO SERVICO (ID,DESCRICAO,VALORSERVICO) VALUES (1,"SERVICO DE INJEÇÃO ELETRONICA",98);
INSERT INTO SERVICO (ID,DESCRICAO,VALORSERVICO) VALUES (2,"SERVICO DE CARBURAÇÃO",40);
INSERT INTO SERVICO (ID,DESCRICAO,VALORSERVICO) VALUES (3,"SERVICO DE TROCA DA BOMBA D'ÁGUA",60);